name: once
description: Want to run a piece of code once (Only - Week - Month - Year - Any duration)? We got you.
version: 1.0.0
homepage: https://github.com/MostafaSolimanMO/once

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  shared_preferences: ^2.0.13  
  package_info_plus: ^1.4.0
  
dev_dependencies:
  flutter_lints: ^1.0.0